
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/anaconda/envs/lod/Library/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:14 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/anaconda/envs/lod/Library/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1237 (message)"
      - "D:/anaconda/envs/lod/Library/share/cmake-3.31/Modules/CMakeDetermineCUDACompiler.cmake:75 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:14 (project)"
    message: |
      Checking whether the CUDA compiler is NVIDIA using "" matched "nvcc: NVIDIA \\(R\\) Cuda compiler driver":
      nvcc: NVIDIA (R) Cuda compiler driver
      Copyright (c) 2005-2023 NVIDIA Corporation
      Built on Wed_Feb__8_05:53:42_Coordinated_Universal_Time_2023
      Cuda compilation tools, release 12.1, V12.1.66
      Build cuda_12.1.r12.1/compiler.32415258_0
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/anaconda/envs/lod/Library/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1237 (message)"
      - "D:/anaconda/envs/lod/Library/share/cmake-3.31/Modules/CMakeDetermineCUDACompiler.cmake:75 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:14 (project)"
    message: |
      Checking whether the CUDA compiler is NVIDIA using "" matched "nvcc: NVIDIA \\(R\\) Cuda compiler driver":
      nvcc: NVIDIA (R) Cuda compiler driver
      Copyright (c) 2005-2023 NVIDIA Corporation
      Built on Wed_Feb__8_05:53:42_Coordinated_Universal_Time_2023
      Cuda compilation tools, release 12.1, V12.1.66
      Build cuda_12.1.r12.1/compiler.32415258_0
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/anaconda/envs/lod/Library/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1237 (message)"
      - "D:/anaconda/envs/lod/Library/share/cmake-3.31/Modules/CMakeDetermineCUDACompiler.cmake:75 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:14 (project)"
    message: |
      Checking whether the CUDA compiler is NVIDIA using "" matched "nvcc: NVIDIA \\(R\\) Cuda compiler driver":
      nvcc: NVIDIA (R) Cuda compiler driver
      Copyright (c) 2005-2023 NVIDIA Corporation
      Built on Wed_Feb__8_05:53:42_Coordinated_Universal_Time_2023
      Cuda compilation tools, release 12.1, V12.1.66
      Build cuda_12.1.r12.1/compiler.32415258_0
...
